# Generated by Django 4.2.1 on 2023-05-18 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='name')),
                ('last_name', models.CharField(max_length=50, verbose_name='last name')),
                ('phone_number', models.IntegerField(verbose_name='phone number')),
                ('email', models.EmailField(max_length=50, verbose_name='email')),
            ],
            options={
                'verbose_name': 'client',
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.DateTimeField()),
                ('appointment_type', models.CharField(choices=[('haircut', 'Haircut'), ('manicure', 'Manicure'), ('pedicure', 'Pedicure'), ('hairstyling', 'Hairstyling'), ('makeup', 'Makeup')], max_length=50)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.client')),
            ],
            options={
                'verbose_name': 'appointment',
            },
        ),
    ]
